languageCode = "en-us"
baseUrl = "/"
title = "john-shiver"
themesDir = "themes/"
theme = "m10c"
paginate = 10

[params]
  author = "John Shiver"
  description = "Writing Software in NYC"
  [[params.social]]
    name = "github"
    url = "https://github.com/johnshiver"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/TrustyJohn"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/johnshiver/"

