baseUrl = "http://www.johnshiver.org"
title = "john-shiver"
theme = "m10c"
paginate = 5
googleAnalytics = "UA-144264343-1"

[params]
  author = "John Shiver"
  description = "Writing Python + Go in NYC"
  [[params.social]]
    name = "github"
    url = "https://github.com/johnshiver"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/TrustyJohn"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/johnshiver/"

